services:
  - type: web
    name: dalilak-ai-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
